### ISSUE TITLE
All badges are displaying `unknown`

### ISSUE THREAD

**Issue by czy-29** [deps-rs/deps.rs#235]
![image](https://github.com/user-attachments/assets/594e4459-7619-44e6-b748-e2a2a1ff00b0)

Is this due to a bug or planned server maintenance? Do you have any ideas?

**Comment by paolobarbolini** [comment]
Thank you for the report. There was a panic in production that poisoned one of the std mutexes and broke everything. I've restarted it now. In case you still see unknown badges it may be of the CDN caching the requests for a while.

```
Aug 07 00:45:54.769 INFO time: 8ms, status: 200 OK, path: /crate/mdns-sd/0.11.1
Aug 07 00:45:56.019 INFO time: 47ms, status: 200 OK, path: /crate/oni-comb-parser-rs/0.0.492
Aug 07 00:46:07.890 INFO time: 117ms, status: 200 OK, path: /crate/rfd/0.14.0/status.svg
Aug 07 00:46:24.167 INFO time: 467ms, status: 200 OK, path: /repo/github/RustCrypto/SSH/status.svg
Aug 07 00:46:31.925 INFO time: 356ms, status: 200 OK, path: /repo/github/baoyachi/simple-log/status.svg
Aug 07 00:46:34.620 INFO time: 88ms, status: 200 OK, path: /repo/github/tokio-rs/prost/status.svg
Aug 07 00:46:38.200 INFO time: 191ms, status: 200 OK, path: /repo/github/fschutt/printpdf/status.svg
Aug 07 00:46:39.078 INFO time: 64ms, status: 200 OK, path: /crate/deno_websocket/0.169.0
Aug 07 00:46:42.015 INFO time: 61ms, status: 200 OK, path: /repo/github/deps-rs/deps.rs
Aug 07 00:46:44.992 INFO time: 472ms, status: 200 OK, path: /repo/github/LiveSplit/livesplit-core
Aug 07 00:46:48.001 INFO time: 0ms, status: 200 OK, path: /crate/windows_aarch64_msvc/0.48.5
thread 'tokio-runtime-worker' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/gix-odb-0.61.0/src/store_impls/dynamic/load_index.rs:374:13:
if the generation changed, the slot index must have changed for sure
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aug 07 00:47:05.338 ERRO error: task 12672 panicked, path: /crate/actix-rt/2.10.0/status.svg
Aug 07 00:47:05.339 INFO time: 19ms, status: 200 OK, path: /crate/actix-rt/2.10.0/status.svg
thread 'tokio-runtime-worker' panicked at src/utils/index.rs:27:39:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
thread 'Aug 07 00:47:10.481 ERRO error: task 12677 panicked, path: /repo/sourcehut/~alip/syd/status.svg
tokio-runtime-worker' panicked at src/utils/index.rs:27:39:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
thread 'tokio-runtime-worker' panicked at src/utils/index.rs:27:39:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
thread 'tokio-runtime-worker' panicked at src/utils/index.rs:27:39:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
thread 'tokio-runtime-worker' panicked at src/utils/index.rs:27:39:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
thread 'tokio-runtime-worker' panicked at src/utils/index.rs:27:39:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
thread 'tokio-runtime-worker' panicked at src/utils/index.rs:27:39:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
thread 'tokio-runtime-worker' panicked at src/utils/index.rs:27:39:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
thread 'tokio-runtime-worker' panicked at src/utils/index.rs:27:39:
called `Result::unwrap()` on an `Err` value: PoisonError { .. }
```

**Comment by cakebaker** [comment]
@paolobarbolini It looks like this issue reappeared.

**Comment by czy-29** [comment]
It seems that the server has crashed again...
![image](https://github.com/user-attachments/assets/3eb6f164-f6ff-440d-a9bd-ea62f32ed4b9)
